export const COLORS = {
  BACKGROUND: '#cfcfcf',
  SHADOW: '#000000',
  MESSAGE_WIN: '#ffffff',
  MESSAGE_LOSE: '#ff0000',
  TIMER_NORMAL: '#FFFFFF',
  TIMER_DANGER: '#F32013',
  ENEMY_GUN_FIRE: 0xff0000,
  PLAYER_SOUND: 0x00ffff,
};
