export const COLORS = {
  BACKGROUND: '#cfcfcf',
  SHADOW: '#000000',
  MESSAGE_WIN: '#ffffff',
  MESSAGE_LOSE: '#ff0000',
  TIMER_NORMAL: '#FFFFFF',
  TIMER_WARNING: '#F0D500',
  TIMER_DANGER: '#F32013',
};
