export const ENEMY = {
  BOUNDINGSIZE: 90,
  SCALE: 0.25,
  LEGS_WIDTH: 172,
  LEGS_HEIGHT: 124,
  SHOT_DELAY: 1000,
  MOVE_SPEED: 80,
  TURN_SPEED: 85,
  VIEW_ANGLE: 60,
  PROJECTILE_SPEED: 2000,
  PROJECTILE_DURATION: 500,
  STATE: {PATROL: 'PATROL', ENGAGE: 'ENGAGE', INVESTIGATE: 'INVESTIGATE', SWEEP: 'SWEEP', RETURN: 'RETURN'},
};

export const ENEMY_SHOOT = {
  WIDTH: 313,
  HEIGHT: 206,
  HP: 2,
  X_CENTER: 96,
  Y_CENTER: 120,
};

export const ENEMY_STAB = {
  WIDTH: 279,
  HEIGHT: 219,
  HP: 1,
  X_CENTER: 108,
  Y_CENTER: 114,
};
