export const ENEMY = {
  WIDTH: 313,
  HEIGHT: 206,
  XCENTER: 96,
  YCENTER: 120,
  BOUNDINGSIZE: 90,
  SCALE: 0.25,
  HP: 2,
  LEGS_WIDTH: 172,
  LEGS_HEIGHT: 124,
  SHOT_DELAY: 1000,
  MOVE_SPEED: 200,
  TURN_SPEED: 85,
  VIEW_ANGLE: 60,
  PROJECTILE_SPEED: 2000,
  PROJECTILE_DURATION: 500,
  PROJECTILE_DAMAGE: 5,
  STATE: {PATROL: 'PATROL', ENGAGE: 'ENGAGE', INVESTIGATE: 'INVESTIGATE', SWEEP: 'SWEEP', RETURN: 'RETURN'},
};

export const ENEMY_SHOOT = {
  HP: 2,
};

export const ENEMY_STAB = {
  WIDTH: 279,
  HEIGHT: 219,
  HP: 1,
  XCENTER: 108,
  YCENTER: 114,
};
